/**
 * 爽博朋克：渊边行者 - 官方初始装备库与槽位计算规则
 * 依照 e:\匕首心\赛博朋克\爽博朋克：渊边行者.json 官方数据源构建
 */

export interface CyberpunkStarterWeapon {
  id: string
  name: string
  category: 'primary' | 'secondary'
  trait: '敏捷' | '力量' | '灵巧' | '本能' | '风度' | '知识'
  traitKey: 'agility' | 'strength' | 'finesse' | 'instinct' | 'presence' | 'knowledge'
  range: string
  rangeKey: 'melee' | 'veryClose' | 'close' | 'far' | 'veryFar'
  damage: string
  damageType: '物理' | '能量'
  burden: '单手' | '双手' | '副手'
  burdenKey: 'oneHanded' | 'twoHanded' | 'offHand'
  feature: string
  tier: 'T1'
  slots?: number | string // 初始装备默认 0 槽，外置装备可占用槽位
}

export interface CyberpunkStarterArmor {
  id: string
  name: string
  thresholdBonusText: string
  majorThresholdBonus: number
  severeThresholdBonus: number
  baseArmorScore: number
  feature: string
  tier: 'T1'
  slots?: number | string
}

/**
 * 规则槽位解析函数：
 * 不填写、-、——、0，都统一判定为 0 槽（不占用槽位计算）
 */
export function parseSlotCost(val: string | number | null | undefined): number {
  if (val === undefined || val === null) return 0
  if (typeof val === 'number') return isNaN(val) || val < 0 ? 0 : val
  const clean = String(val).trim()
  if (clean === '' || clean === '-' || clean === '——' || clean === '0' || clean === '无' || clean === '0槽') {
    return 0
  }
  const match = clean.match(/\d+/)
  if (match) {
    const num = parseInt(match[0], 10)
    return isNaN(num) ? 0 : num
  }
  return 0
}

/**
 * 16 款主武器（物理类 + 能量类）
 */
export const CYBERPUNK_STARTER_PRIMARY_WEAPONS: CyberpunkStarterWeapon[] = [
  // 物理主武器
  {
    id: 'cb_wp_tactical_knife',
    name: '战术短刀',
    category: 'primary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd8+1',
    damageType: '物理',
    burden: '单手',
    burdenKey: 'oneHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_katana',
    name: '武士刀',
    category: 'primary',
    trait: '敏捷',
    traitKey: 'agility',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd10+3',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_needle',
    name: '突刺针',
    category: 'primary',
    trait: '风度',
    traitKey: 'presence',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd8',
    damageType: '物理',
    burden: '单手',
    burdenKey: 'oneHanded',
    feature: '**迅捷：**标记 1 压力点，以攻击范围内的一个额外目标。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_breaching_axe',
    name: '破门重斧',
    category: 'primary',
    trait: '力量',
    traitKey: 'strength',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd10+3',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_power_hammer',
    name: '动力锤',
    category: 'primary',
    trait: '力量',
    traitKey: 'strength',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd12+3',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '**重型：**闪避值 -1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_riot_baton',
    name: '防暴棍',
    category: 'primary',
    trait: '本能',
    traitKey: 'instinct',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd10+3',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_man_catcher',
    name: '防暴叉',
    category: 'primary',
    trait: '力量',
    traitKey: 'strength',
    range: '邻近',
    rangeKey: 'veryClose',
    damage: 'd10+2',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '**繁琐：**灵巧 -1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_pistol',
    name: '手枪',
    category: 'primary',
    trait: '本能',
    traitKey: 'instinct',
    range: '远距离',
    rangeKey: 'far',
    damage: 'd6+1',
    damageType: '物理',
    burden: '单手',
    burdenKey: 'oneHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_shotgun',
    name: '霰弹枪',
    category: 'primary',
    trait: '力量',
    traitKey: 'strength',
    range: '近距离',
    rangeKey: 'close',
    damage: 'd6+2',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '**散射：**当你进行攻击时，以你前方射程内的所有生物作为目标。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_rifle',
    name: '步枪',
    category: 'primary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '极远',
    rangeKey: 'veryFar',
    damage: 'd8+3',
    damageType: '物理',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '**繁琐：**灵巧 -1。',
    tier: 'T1',
    slots: 0,
  },

  // 能量主武器
  {
    id: 'cb_wp_shock_fist',
    name: '冲击拳套',
    category: 'primary',
    trait: '力量',
    traitKey: 'strength',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd10+3',
    damageType: '能量',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_arc_pistol',
    name: '电弧手枪',
    category: 'primary',
    trait: '本能',
    traitKey: 'instinct',
    range: '近距离',
    rangeKey: 'close',
    damage: 'd8+1',
    damageType: '能量',
    burden: '单手',
    burdenKey: 'oneHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_pulse_rifle',
    name: '脉冲步枪',
    category: 'primary',
    trait: '本能',
    traitKey: 'instinct',
    range: '远距离',
    rangeKey: 'far',
    damage: 'd6+3',
    damageType: '能量',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_mag_blade',
    name: '磁吸飞刃',
    category: 'primary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '近距离',
    rangeKey: 'close',
    damage: 'd8',
    damageType: '能量',
    burden: '单手',
    burdenKey: 'oneHanded',
    feature: '**磁吸回收：**投掷攻击完成后，飞刃会立刻自动飞回手中。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_cluster_laser',
    name: '便携式集束激光',
    category: 'primary',
    trait: '知识',
    traitKey: 'knowledge',
    range: '极远',
    rangeKey: 'veryFar',
    damage: 'd6',
    damageType: '能量',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '**强力：**伤害掷骰时额外掷一枚伤害骰，并去掉其中最小的一个。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_wp_wrist_pulse',
    name: '手腕脉冲',
    category: 'primary',
    trait: '敏捷',
    traitKey: 'agility',
    range: '邻近',
    rangeKey: 'veryClose',
    damage: 'd10+2',
    damageType: '能量',
    burden: '双手',
    burdenKey: 'twoHanded',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
]

/**
 * 9 款副武器
 */
export const CYBERPUNK_STARTER_SECONDARY_WEAPONS: CyberpunkStarterWeapon[] = [
  {
    id: 'cb_sec_pocket_knife',
    name: '袖珍刀',
    category: 'secondary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd8',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**双持：**近战时主武器伤害 +2。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_tactical_bayonet',
    name: '战术刺刀',
    category: 'secondary',
    trait: '敏捷',
    traitKey: 'agility',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd8',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**双持：**近战时主武器伤害 +2。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_riot_arm_shield',
    name: '防暴臂盾',
    category: 'secondary',
    trait: '力量',
    traitKey: 'strength',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd4',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**保护：**护甲值 +1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_folding_shield',
    name: '折叠重盾',
    category: 'secondary',
    trait: '力量',
    traitKey: 'strength',
    range: '近战',
    rangeKey: 'melee',
    damage: 'd6',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**壁垒：**护甲值 +2，闪避值 -1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_shock_cable',
    name: '电击索',
    category: 'secondary',
    trait: '风度',
    traitKey: 'presence',
    range: '邻近',
    rangeKey: 'veryClose',
    damage: 'd6',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**电击：**标记 1 压力点，将近战范围内的所有敌人逼退至近距离范围。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_grapple_hook',
    name: '战术抓钩',
    category: 'secondary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '近距离',
    rangeKey: 'close',
    damage: 'd6',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**钩爪：**攻击命中后，可将目标拉入你的近战范围内。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_capture_net',
    name: '战术捕网',
    category: 'secondary',
    trait: '敏捷',
    traitKey: 'agility',
    range: '邻近',
    rangeKey: 'veryClose',
    damage: 'd4',
    damageType: '物理',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '**捕捉：**攻击命中时，可选择不造成伤害，改为使目标暂时处于 束缚 和 脆弱 状态。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_taser',
    name: '电击枪',
    category: 'secondary',
    trait: '本能',
    traitKey: 'instinct',
    range: '近距离',
    rangeKey: 'close',
    damage: 'd6+2',
    damageType: '能量',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_sec_palm_cannon',
    name: '掌炮',
    category: 'secondary',
    trait: '灵巧',
    traitKey: 'finesse',
    range: '远距离',
    rangeKey: 'far',
    damage: 'd6+1',
    damageType: '能量',
    burden: '副手',
    burdenKey: 'offHand',
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
]

/**
 * 5 款初始护甲
 */
export const CYBERPUNK_STARTER_ARMORS: CyberpunkStarterArmor[] = [
  {
    id: 'cb_ar_light_lining',
    name: '轻型内衬',
    thresholdBonusText: '+0 / +0',
    majorThresholdBonus: 0,
    severeThresholdBonus: 0,
    baseArmorScore: 3,
    feature: '**灵活：**闪避值 +1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_ar_combat_suit',
    name: '作战服',
    thresholdBonusText: '+1 / +2',
    majorThresholdBonus: 1,
    severeThresholdBonus: 2,
    baseArmorScore: 3,
    feature: '——',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_ar_bulletproof_vest',
    name: '防弹背心',
    thresholdBonusText: '+2 / +4',
    majorThresholdBonus: 2,
    severeThresholdBonus: 4,
    baseArmorScore: 4,
    feature: '**重型：**闪避值 -1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_ar_riot_armor',
    name: '全覆式防暴衣',
    thresholdBonusText: '+3 / +6',
    majorThresholdBonus: 3,
    severeThresholdBonus: 6,
    baseArmorScore: 4,
    feature: '**极重：**闪避值 -2，敏捷 -1。',
    tier: 'T1',
    slots: 0,
  },
  {
    id: 'cb_ar_insulating_suit',
    name: '绝缘防护服',
    thresholdBonusText: '+0 / +0',
    majorThresholdBonus: 0,
    severeThresholdBonus: 0,
    baseArmorScore: 3,
    feature: '**绝缘：**受能量伤害时，在计算伤害阈值前，伤害先减少等同于当前可用护甲槽的数量。',
    tier: 'T1',
    slots: 0,
  },
]
